import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import { Toaster } from "react-hot-toast";
import { ReduxProviders } from "@/providers/ReduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "my-recipes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProviders>
          <TanstackProvider>
            <Navbar />
            {children}
            <Toaster />
          </TanstackProvider>
        </ReduxProviders>
      </body>
    </html>
  );
}
